---
- name: "Build and deploy a Quarkus app using Ansible"
  hosts: all
  gather_facts: true
  become: true
  vars:
    quarkus_app_repo_url: 'https://github.com/amqphub/quarkus-qpid-jms-quickstart.git'
    app_name: quarkus-qpid-jms-quickstart
    quarkus_path_to_folder_to_deploy: /opt/quarkus_deploy
    quarkus_app_workdir: /root/quarkus-qpid-jms-quickstart.git
    quarkus_java_home: /usr/lib/jvm/jdk-17-oracle-x64
    quarkus_app_port: 8090
  collections:
    - middleware_automation.quarkus
  pre_tasks:
    - name: "Build the Quarkus from {{ quarkus_app_repo_url }}."
      ansible.builtin.include_role:
        name: quarkus
        tasks_from: build.yml
  tasks:
    - name: "Deploy Quarkus app on target."
      ansible.builtin.include_role:
        name: quarkus
        tasks_from: deploy.yml
  post_tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: "Check that systemd service demo app is running."
      ansible.builtin.assert:
        that:
          - ansible_facts.services is defined
          - ansible_facts.services["{{ app_name }}.service"] is defined
          - ansible_facts.services["{{ app_name }}.service"]['state'] == 'running'
          - ansible_facts.services["{{ app_name }}.service"]['status'] == 'enabled'
        quiet: true

    - name: "Check that Quarkus app is accessible"
      ansible.builtin.uri:
        url: 'http://localhost:8090/prices.html'
