---
- name: "Build and deploy a Quarkus app using Ansible"
  hosts: quarkus
  gather_facts: true
  become: true
  collections:
    - middleware_automation.quarkus
  pre_tasks:
    - name: "Build the Quarkus from {{ quarkus_app_repo_url }}."
      ansible.builtin.include_role:
        name: quarkus
        tasks_from: build.yml
    - name: Creating a file with content
      copy:
        dest: "{{ quarkus_app_workdir }}/.env"
        content: |
          GREETING_WILDFLY_VM_IP={{ wildfly_vm_ip }}
  tasks:
    - name: "Deploy Quarkus app on target."
      ansible.builtin.include_role:
        name: quarkus
        tasks_from: deploy.yml
  post_tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: "Check that systemd service demo app is running."
      ansible.builtin.assert:
        that:
          - ansible_facts.services is defined
          - ansible_facts.services["{{ app_name }}.service"] is defined
          - ansible_facts.services["{{ app_name }}.service"]['state'] == 'running'
          - ansible_facts.services["{{ app_name }}.service"]['status'] == 'enabled'
        quiet: true

    - name: "Check that Quarkus app is accessible"
      ansible.builtin.uri:
        url: 'http://0.0.0.0:9000/prices.html'
