---
- name: Ensure Wildfly is install and running as a service
  hosts: wildfly
  gather_facts: true
  become: true
  collections:
    - middleware_automation.wildfly
  roles:
    - middleware_automation.wildfly.wildfly_install
    - middleware_automation.wildfly.wildfly_systemd
  pre_tasks:
    - name: "Remove previous standalone configuration {{ configuration_file }}"
      ansible.builtin.file:
        path: "{{ configuration_file }}"
        state: absent
  tasks:
    - name: Create user and group for the quarkus jms client
      ansible.builtin.shell: ./add-user.sh -a -u "{{ app_user }}" -p "{{ app_pass }}" -g "{{ app_group }}"
      args:
        chdir: "{{ wildfly_home }}/bin"
  
  post_tasks:
    - name: "Deploy apps"
      when:
        - app_deploy_enabled
      block:
        - name: "Download {{ app | length }} webapps."
          ansible.builtin.get_url:
            url: "{{ app[0].url }}"
            dest: "{{ wildfly_install_workdir }}/{{ app[0].name }}"

        - name: "Deploy {{ app | length }} webapp(s)"
          ansible.builtin.include_role:
            name: wildfly_utils
            tasks_from: jboss_cli.yml
          vars:
            jboss_home: "{{ wildfly_home }}"
            jboss_cli_query: "'deploy --force {{ wildfly_install_workdir }}/{{ app[0].name }}'"
